  properties:
    wowprogress:
      url: "https://www.wowprogress.com/gearscore/?lfg=1&sortby=ts"
      limit: 10


  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/wowdatacrawler
      username: postgres
      password: pass
    jpa:
      hibernate:
        ddl-auto: create
    flyway:
      enabled: true
      clean-disabled: true
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: https://example.com/.well-known/jwks.json
